# so basically a think that the job is where we create
# the pipeline steps, so a docker image are created and
# the pipeline are executed, passing for all the steps
# defined by this script
image: maven

build:
stage: build
  script:
  - mvn package -Dmaven.test.skip

