# so basically a think that the job is where we create
# the pipeline steps, so a docker image are created and
# the pipeline are executed, passing for all the steps
# defined by this script

job:
  script:
  - echo "Olá alunos estamos aprendendo sobre pipeline"
  - echo "Este é um teste"
build:
  script:
  - echo "mais um teste"